CREATE DATABASE IF NOT EXISTS BOOKPADEL;
USE BOOKPADEL;
CREATE TABLE IF NOT EXISTS Usuarios (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDOS VARCHAR(200) NOT NULL,
    RANGO VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(200) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    NOMBRE_DE_USUARIO VARCHAR(200) NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    NIVEL_DE_PADEL VARCHAR(20) NOT NULL,
    POSICION_PISTA VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS Eventos (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    PRECIO DOUBLE UNSIGNED NOT NULL,
    TELEFONO_ORGANIZADOR INT NOT NULL, 
    FECHA VARCHAR(200) NOT NULL,
    FECHA_NUMERICA DATE NOT NULL,
    PARTICIPANTES_ACTUALES INT UNSIGNED DEFAULT 0,
    CATEGORIA_1 DOUBLE NOT NULL,
    CATEGORIA_2 DOUBLE,
    CATEGORIA_3 DOUBLE,
    CATEGORIA_4 DOUBLE,
    CATEGORIA_5 DOUBLE,
    CATEGORIA_6 DOUBLE,
    CATEGORIA_7 DOUBLE,
    CATEGORIA_FEMENINA DOUBLE,
    DIRECCION VARCHAR(200) NOT NULL,
    PREMIO INT,
    PORTADA BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS Inscripciones (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_JUGADOR_UNO VARCHAR (200) NOT NULL,
    APELLIDOS_JUGADOR_UNO VARCHAR (200) NOT NULL,
    TELEFONO_JUGADOR_UNO VARCHAR (20) NOT NULL,
    NOMBRE_JUGADOR_DOS VARCHAR (200) NOT NULL,
    APELLIDOS_JUGADOR_DOS VARCHAR (200) NOT NULL,
    TELEFONO_JUGADOR_DOS VARCHAR (20) NOT NULL,
    CATEGORIA VARCHAR (20) NOT NULL,
    ID_EVENTO INT UNSIGNED,
    Foreign Key (ID_EVENTO) references Eventos(ID)
);