CREATE DATABASE IF NOT EXISTS BOOKPADEL;
USE BOOKPADEL;
CREATE TABLE IF NOT EXISTS Usuarios (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDOS VARCHAR(200) NOT NULL,
    RANGO VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(200) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    NOMBRE_DE_USUARIO VARCHAR(200) NOT NULL,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    NIVEL_DE_PADEL VARCHAR(20) NOT NULL,
    POSICION_PISTA VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS Eventos (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    PRECIO DOUBLE UNSIGNED NOT NULL,
    TELEFONO_ORGANIZADOR INT NOT NULL, 
    FECHA VARCHAR(200) NOT NULL,
    PARTICIPANTES_MAXIMO INT UNSIGNED NOT NULL,
    PARTICIPANTES_ACTUALES INT UNSIGNED DEFAULT 0,
    CATEGORIA_MIN DOUBLE NOT NULL,
    CATEGORIA_MAX DOUBLE NOT NULL,
    DIRECCION VARCHAR(200),
    INSTAGRAM TEXT,
    PREMIO INT,
    PORTADA BLOB
    REGLAMENTO TEXT,
    LINK_FOTOS
);