CREATE DATABASE IF NOT EXISTS BOOKPADEL;
USE BOOKPADEL;
CREATE TABLE IF NOT EXISTS Usuarios (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    APELLIDOS VARCHAR(200) NOT NULL,
    RANGO VARCHAR(50) NOT NULL, 
    EMAIL VARCHAR(200) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    NOMBRE_DE_USUARIO VARCHAR(200) NOT NULL UNIQUE,
    CONTRASEÑA VARCHAR(255) NOT NULL,
    NIVEL_DE_PADEL VARCHAR(20) NOT NULL,
    POSICION_PISTA VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS Eventos (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    PRECIO DOUBLE UNSIGNED NOT NULL,
    FECHA VARCHAR(200) NOT NULL,
    FECHA_NUMERICA DATE NOT NULL,
    PARTICIPANTES_ACTUALES INT UNSIGNED DEFAULT 0,
    CATEGORIA_MASCULINA_1_1 DOUBLE,
    CATEGORIA_MASCULINA_1_2 DOUBLE,
    CATEGORIA_MASCULINA_2_1 DOUBLE,
    CATEGORIA_MASCULINA_2_2 DOUBLE,
    CATEGORIA_MASCULINA_3_1 DOUBLE,
    CATEGORIA_MASCULINA_3_2 DOUBLE,
    CATEGORIA_MASCULINA_4_1 DOUBLE,
    CATEGORIA_MASCULINA_4_2 DOUBLE,
    CATEGORIA_MASCULINA_5_1 DOUBLE,
    CATEGORIA_MASCULINA_5_2 DOUBLE,
    CATEGORIA_MASCULINA_6_1 DOUBLE,
    CATEGORIA_MASCULINA_6_2 DOUBLE,
    CATEGORIA_MIXTA_1_1 DOUBLE,
    CATEGORIA_MIXTA_1_2 DOUBLE,
    CATEGORIA_MIXTA_2_1 DOUBLE,
    CATEGORIA_MIXTA_2_2 DOUBLE,
    CATEGORIA_MIXTA_3_1 DOUBLE,
    CATEGORIA_MIXTA_3_2 DOUBLE,
    CATEGORIA_MIXTA_4_1 DOUBLE,
    CATEGORIA_MIXTA_4_2 DOUBLE,
    CATEGORIA_MIXTA_5_1 DOUBLE,
    CATEGORIA_MIXTA_5_2 DOUBLE,
    CATEGORIA_MIXTA_6_1 DOUBLE,
    CATEGORIA_MIXTA_6_2 DOUBLE,
    CATEGORIA_FEMENINA_1_1 DOUBLE,
    CATEGORIA_FEMENINA_1_2 DOUBLE,
    CATEGORIA_FEMENINA_2_1 DOUBLE,
    CATEGORIA_FEMENINA_2_2 DOUBLE,
    CATEGORIA_FEMENINA_3_1 DOUBLE,
    CATEGORIA_FEMENINA_3_2 DOUBLE,
    CATEGORIA_FEMENINA_4_1 DOUBLE,
    CATEGORIA_FEMENINA_4_2 DOUBLE,
    CATEGORIA_FEMENINA_5_1 DOUBLE,
    CATEGORIA_FEMENINA_5_2 DOUBLE,
    CATEGORIA_FEMENINA_6_1 DOUBLE,
    CATEGORIA_FEMENINA_6_2 DOUBLE,
    DIRECCION VARCHAR(100),
    PORTADA BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS Inscripciones (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_JUGADOR_UNO VARCHAR (200) NOT NULL,
    APELLIDOS_JUGADOR_UNO VARCHAR (200) NOT NULL,
    TELEFONO_JUGADOR_UNO VARCHAR (20) NOT NULL,
    NOMBRE_DE_USUARIO_DOS VARCHAR (150),
    CATEGORIA VARCHAR (100) NOT NULL,
    ID_EVENTO INT UNSIGNED,
    Foreign Key (ID_EVENTO) references Eventos(ID)
);


-- bugfix =====> eliminar eventos (cambiamos a borrado en cascada)

ALTER TABLE Inscripciones
DROP FOREIGN KEY inscripciones_ibfk_1,
ADD CONSTRAINT nueva_restriccion_fk
FOREIGN KEY (ID_EVENTO)
REFERENCES Eventos(ID)
ON DELETE CASCADE;
